# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 18:14
from __future__ import unicode_literals

import Professor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserAuth', '0005_auto_20180912_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConductQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_quiz_id', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('conduction_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CourseProfessor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Professor.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=100)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Professor.Course')),
            ],
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=100)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Professor.Poll')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.CharField(blank=True, max_length=1000, null=True)),
                ('date_of_birth', models.DateField()),
                ('address_city', models.CharField(max_length=200)),
                ('address_district', models.CharField(max_length=200)),
                ('address_state', models.CharField(max_length=200)),
                ('address_country', models.CharField(max_length=200)),
                ('address_pincode', models.IntegerField(blank=True, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='/PROFESSOR-PROFILE-PIC-DIRECTORY/professor_avatar.png', null=True, upload_to=Professor.models.get_professor_profile_pic_path)),
                ('qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('email_address_verified', models.BooleanField(default=False)),
                ('mobile_no_address_verified', models.BooleanField(default=False)),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserAuth.GenderChoice')),
                ('institute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserAuth.InstituteProfile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ProfessorProf', to='UserAuth.ProfessorAuthProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('pass_marks', models.IntegerField(default=0)),
                ('max_marks', models.IntegerField(default=0)),
                ('no_of_questions', models.IntegerField(default=0)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Professor.Course')),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Professor.ProfessorProfile')),
            ],
        ),
        migrations.CreateModel(
            name='QuizOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('question_file', models.ImageField(blank=True, null=True, upload_to='')),
                ('marks', models.IntegerField(default=0)),
                ('time', models.IntegerField(default=0)),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Professor.Quiz')),
            ],
        ),
        migrations.AddField(
            model_name='quizoptions',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Professor.QuizQuestion'),
        ),
        migrations.AddField(
            model_name='quizoptions',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Professor.Quiz'),
        ),
        migrations.AddField(
            model_name='poll',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Professor.ProfessorProfile'),
        ),
        migrations.AddField(
            model_name='courseprofessor',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Professor.ProfessorProfile'),
        ),
        migrations.AddField(
            model_name='conductquiz',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Professor.Quiz'),
        ),
    ]
