# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-16 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Professor', '0006_auto_20181016_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizquestion',
            old_name='is_multipl_correct',
            new_name='is_multiples_correct',
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
