# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-16 18:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Professor', '0008_auto_20181016_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='is_multiple_correct',
        ),
    ]
