# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-16 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Professor', '0009_remove_quizquestion_is_multiple_correct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='title',
        ),
    ]
