# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-17 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Professor', '0011_remove_quizquestion_no_of_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='unique_quiz_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
