# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-18 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Professor', '0012_quiz_unique_quiz_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
