# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 18:14
from __future__ import unicode_literals

import Student.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserAuth', '0005_auto_20180912_1702'),
        ('Professor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Professor.Course')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.CharField(blank=True, max_length=1000, null=True)),
                ('date_of_birth', models.DateField()),
                ('address_city', models.CharField(max_length=200)),
                ('address_district', models.CharField(max_length=200)),
                ('address_state', models.CharField(max_length=200)),
                ('address_country', models.CharField(max_length=200)),
                ('address_pincode', models.IntegerField(blank=True, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='/STUDENT-PROFILE-PIC-DIRECTORY/student_avatar.png', null=True, upload_to=Student.models.get_student_profile_pic_path)),
                ('email_address_verified', models.BooleanField(default=False)),
                ('mobile_no_address_verified', models.BooleanField(default=False)),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserAuth.GenderChoice')),
                ('institute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserAuth.InstituteProfile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='StudentProf', to='UserAuth.StudentAuthProfile')),
            ],
        ),
        migrations.AddField(
            model_name='coursestudent',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Student.StudentProfile'),
        ),
    ]
