# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-06 18:48
from __future__ import unicode_literals

import Student.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_remove_studentprofile_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/STUDENT-PROFILE-PIC-DIRECTORY/student_avatar.png', null=True, upload_to=Student.models.get_student_profile_pic_path),
        ),
    ]
