# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-19 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doubt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubt',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
