# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-05 15:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenderChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstituteProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('address_city', models.CharField(max_length=200)),
                ('address_district', models.CharField(max_length=200)),
                ('address_state', models.CharField(max_length=200)),
                ('address_country', models.CharField(max_length=200)),
                ('address_pincode', models.IntegerField()),
                ('email_address', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessorAuthProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.IntegerField(blank=True, null=True)),
                ('date_of_birth', models.DateField()),
                ('email_address', models.CharField(max_length=100)),
                ('otp', models.IntegerField(default=0)),
                ('otp_sent_to_email', models.BooleanField(default=False)),
                ('otp_sent_to_mobile_no', models.BooleanField(default=False)),
                ('otp_verified', models.BooleanField(default=False)),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserAuth.GenderChoice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAuthProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.IntegerField(blank=True, null=True)),
                ('date_of_birth', models.DateField()),
                ('email_address', models.CharField(max_length=100)),
                ('otp', models.IntegerField(default=0)),
                ('otp_sent_to_email', models.BooleanField(default=False)),
                ('otp_sent_to_mobile_no', models.BooleanField(default=False)),
                ('otp_verified', models.BooleanField(default=False)),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserAuth.GenderChoice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
