# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-10 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0002_auto_20180905_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professorauthprofile',
            old_name='otp_sent_to_email',
            new_name='email_verfied',
        ),
        migrations.RenameField(
            model_name='studentauthprofile',
            old_name='otp_sent_to_email',
            new_name='email_verfied',
        ),
        migrations.AddField(
            model_name='professorauthprofile',
            name='email_verification_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='professorauthprofile',
            name='email_verification_link_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentauthprofile',
            name='email_verification_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentauthprofile',
            name='email_verification_link_sent',
            field=models.BooleanField(default=False),
        ),
    ]
