# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-12 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0003_auto_20180910_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professorauthprofile',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='studentauthprofile',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
